import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.scss";
import Bg from "@/components/Bg/Bg";

const nunito = Nunito({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
	title: "next-firebase-chat",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={nunito.className} suppressHydrationWarning>
				<Bg>{children}</Bg>
			</body>
		</html>
	);
}
